### ISSUE TITLE
Barrel Edges Are See-Through

### ISSUE THREAD

**Issue by faevyn** [chimericdream/minekea#42]
![image](https://user-images.githubusercontent.com/93735226/172245931-7fc3a2a3-31ad-43e7-8049-00ab4547a1e0.png)

The barrels, when highlighted, show through them (applies to all barrels, just showing one in the screenshot). Also unsure if this is something I can fix elsewhere, however when using a shader it shows through them and you can see cave systems below the ground. I figure the shader issue isn't something you can fix but wanted to mention it if it is part of the above.

![image](https://user-images.githubusercontent.com/93735226/172246212-cae94522-6850-4d86-9e20-feb57e4caf93.png)

**Comment by faevyn** [comment]
This is on 1.18.2 using Fabric and AARP installed.

**Comment by chimericdream** [comment]
Can you post your mod list? I just tested in a mostly vanilla instance with Minekea + BYG, and I didn't see the gap in the texture when highlighting the barrels.

As for the see-through texture, I suspect you are correct. I use an overlay texture for barrels, which requires me to register the blocks as translucent, but only the outer layer has any kind of transparency on it. The underlying texture is and should be completely opaque. My guess is the shader is doing something where it gets the outer texture of a block and applies the opacity to it entirely. I don't use shaders, but I can take a look if you give me the info about your setup. That said, I'm not entirely hopeful about being able to fix the issue, because to me it seems like a bug in the shader itself (easy to say, right).

**Comment by faevyn** [comment]
I had removed that instance a little bit ago cause I goofed a texture pack I was personally making but I did remember this not working on a different instance with specific mods so I went and installed them again just to check and make sure.

Mods List:
ARRP 0.5.7
Fabric API 0.55.1+1.18.2
Iris 1.18.2-1.2.5
Minekea - 1.18.2-2.8.0
Sodium Fabric - 1.18.2-0.4.1+build.15
Xaero's Minimap 22.9.0 1.18.2
Xaero's World Map 1.23.1 1.18.2

For shaders I'm using Sildur's Vibrant Shaders v1.32+Medium but happens with High/Low.

https://sildurs-shaders.github.io/downloads/

**Comment by chimericdream** [comment]
Thanks for the list. I'll see what I can figure out.

**Comment by chimericdream** [comment]
I can confirm that the issue happens with Sodium installed, but I haven't figured out _why_ yet. I don't know if there's a bug in Sodium or if there's something I can change about how my textures are generated that won't have this effect in that scenario.

I'll keep researching and let you know.

**Comment by faevyn** [comment]
Thank you so much for not only your fast responses but for looking into this!

**Comment by chimericdream** [comment]
Reported to the Sodium devs. I will leave this issue open until they respond and let me know if this is a confirmed bug on their end or mine.

https://github.com/CaffeineMC/sodium-fabric/issues/1326

**Comment by woalk** [comment]
It has to do with the way the block models are created for compressed blocks and barrels. You create them by setting their render layer to `Translucent`, and then overlaying a transparent overlay image on top of the regular texture. Sodium and various shaders interpret this differently than Vanilla Minecraft, mainly because of the `Translucent` render layer that they do not expect for solid blocks.

Without changing Sodium, Iris or the shader code, fixing this would probably entail creating regular block models for all compressed blocks and barrels with pre-built textures, instead of dynamically creating them with the `Translucent` render layer.
