### ISSUE TITLE
Broken translation strings with mods that add its own language files to minecraft namespace

### ISSUE THREAD

**Issue by SplendidAlakey** [chimericdream/minekea#67]
**Describe the bug**

When Minekea is installed together with [Better Biome Blend](https://modrinth.com/mod/better-biome-blend), many translation strings break.

**To Reproduce**

1. Install both mods and it's requirements
2. Grab a vertical oak bookshelf stairs as an example and look at its name

**Expected behavior**

Proper names for all blocks.

**Screenshots**

![2022-08-26_18 05 20](https://user-images.githubusercontent.com/86702831/186948309-6b7df293-6f43-436f-acd9-bc4755b37683.png)
![2022-08-26_18 08 56](https://user-images.githubusercontent.com/86702831/186948320-6ecbfcb5-f44d-40f0-8116-907a90b1dbee.png)

**Environment**

 * Minecraft version: 1.19.2
 * Minekea version: 3.3.3
 * OS: W10

**Additional context**

Logs: https://gist.github.com/SplendidAlakey/6197209bf57e7aae4124e0123fd85c67

Reported to BBB as well: https://github.com/FionaTheMortal/better-biome-blend/issues/61

**Comment by chimericdream** [comment]
That's super weird. I'll see if I can figure out what's going on and whether it is something on my end or theirs.

Thanks for the report!

**Comment by chimericdream** [comment]
I'm at work now, so I can't dig into the code, but I took a quick glance at your logs. Nothing jumps out that immediately looks like it could cause this particular issue, but I did notice a bunch of errors around the end stone/cobbled end stone entries that I should take care of. _Maybe_ there's something weird happening that stems from that? It's hard to say, but I will try to look at it this weekend.

**Comment by Footage2-Amply-Pounce** [comment]
Oh, sorry, I forgot to try to reproduce the issue with default config settings 🤦‍♂️ I have `"enableCobbledEndStone"` set to `false`. That still shouldn't produce those errors, though, right? I'll be back in a couple of minutes to see if having default configs solves the issue.

**Comment by Footage2-Amply-Pounce** [comment]
Yeah the log spam was caused by disabling cobbled endstone, here are much cleaner logs with default settings: https://gist.github.com/Footage2-Amply-Pounce/659c9765f9018718a3a8c8024fed1a0b. This shouldn't happen anyway, but I see that you opened a separate issue for it.

The original issue still persists, though, the items have untranslated strings.

**Comment by Footage2-Amply-Pounce** [comment]
Just found out that [Consistency+](https://www.curseforge.com/minecraft/mc-mods/consistencyplus) causes the same effect, created an issue on their side here: https://github.com/ConsistencyPlus/ConsistencyPlus/issues/132

Logs for C+: https://gist.github.com/Footage2-Amply-Pounce/cb3f7fd508e37ffcaccd87aeee5cd5e8

**Comment by Cart3r1234** [comment]
While I'm not sure the definite cause of the issue, this may have to do with Consistency+ and/or other mods providing a lang in the minecraft directory to override vanilla block translation strings.  Perhaps any mod that has a lang file in the minecraft namespace breaks this mod's translations?

While ours doesn't modify any of the strings affected in the screenshot, perhaps there's a conflict caused by trying to add to or replace things present in the vanilla lang files.

**Comment by Footage2-Amply-Pounce** [comment]
> [...] this may have to do with Consistency+ and/or other mods providing a lang in the minecraft directory to override vanilla block translation strings [...]

Your assumption seems to be correct. I removed the lang files from C+ and BBB, which solved the issue.

BBB's lang files don't touch in game items at all, only menu strings: https://github.com/FionaTheMortal/better-biome-blend/tree/1.18.2-forge/src/main/resources/assets/minecraft/lang
